/**
 * Metabase public embed URLs for each chart card.
 * Generated by metabase/setup_metabase.py — re-run that script to refresh.
 */
export type MetabaseChart = {
  id: string
  title: string
  description: string
  url: string
}

export const METABASE_BASE_URL =
  import.meta.env.VITE_METABASE_URL ?? 'http://localhost:3000'

export const metabaseCharts: MetabaseChart[] = [
  {
    id: "by-property-type",
    title: "Average Price by Property Type",
    description: "Mean sale price for each property type.",
    url: "http://127.0.0.1:3000/public/question/287d6a00-8ce9-44ba-9f45-218bb4322c61",
  },
  {
    id: "price-distribution",
    title: "Price Distribution",
    description: "Sale price buckets excluding Other and top 1% approx (price <= 1.2M).",
    url: "http://127.0.0.1:3000/public/question/a0b92a26-fb0c-45eb-94f9-1f89444299f3",
  },
  {
    id: "monthly-trend",
    title: "Monthly Volume vs Median Price",
    description: "Transaction count and median price by month.",
    url: "http://127.0.0.1:3000/public/question/c67a75d7-e4ff-426d-b10f-2e7420e41cff",
  },
  {
    id: "district-most-expensive",
    title: "Most Expensive Districts",
    description: "Top 15 districts by average price (min 15 sales).",
    url: "http://127.0.0.1:3000/public/question/e2678b63-c13d-43cc-a0ec-5c7a3d48afec",
  },
  {
    id: "district-least-expensive",
    title: "Least Expensive Districts",
    description: "Bottom 15 districts by average price (min 15 sales).",
    url: "http://127.0.0.1:3000/public/question/172b076c-1252-4d69-b970-ac4c789cf208",
  },
  {
    id: "freehold-leasehold",
    title: "Freehold vs Leasehold",
    description: "Average price by tenure.",
    url: "http://127.0.0.1:3000/public/question/ff563278-a227-4b08-8c26-2a5a4ec897bb",
  },
  {
    id: "leasehold-share",
    title: "Leasehold Share by Property Type",
    description: "Percent of sales that are leasehold within each property type.",
    url: "http://127.0.0.1:3000/public/question/732d7132-412c-40b7-bdcd-c88145447f32",
  },
  {
    id: "new-build-premium",
    title: "New-Build Premium by Property Type",
    description: "Percent premium of new builds vs existing stock.",
    url: "http://127.0.0.1:3000/public/question/e8778ae8-2d18-4eaa-b9df-94950dd05a82",
  },
]
